name: "Build For Template"
on:
  workflow_call:
    inputs:
      self-hosted:
        required: true
        type: boolean
      label:
        required: true
        type: string
      language:
        required: true
        type: string
      working-repo:
        required: true
        type: string
      image-name:
        required: true
        type: string
    #secrets:
    #  envPAT:
    #    required: true

jobs:
  check-inputs: 
    name: Check Inputs
    runs-on: ${{ inputs.label}} 
    steps:
    - name: Display Inputs 
      run: | 
        echo ${{ inputs.self-hosted}}
        echo ${{ inputs.label}}
        echo ${{ inputs.language}}
        echo ${{ inputs.working-repo}}
        echo ${{ inputs.image-name}}
  java-build:
    runs-on: ${{ inputs.label}} 
    name: "Branch build"
    steps:
        - uses: actions/checkout@v3
        - name: Set up Maven
          if: ${{ inputs.language }} == 'java' && ${{ inputs.self-hosted }} == true
          uses: stCarolas/setup-maven@v4.4
          with:
            maven-version: 3.8.2
        - name: Set up JDK 17
          if: ${{ inputs.language }} == 'java'
          uses: actions/setup-java@v3
          with:
              distribution: 'temurin'
              java-version: 17
              architecture: x64
        - name: Test with Maven
          if: ${{ inputs.language }} == 'java'
          run: mvn --no-transfer-progress verify
        - name: Set up Docker Buildx
          if: ${{ inputs.self-hosted }} == true
          uses: docker/setup-buildx-action@v2
        - name: Log in to the Container registry
          uses: docker/login-action@v1
          with:
            registry: ghcr.io # Using Github container repository
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}  
        - name: Build and push Docker image for server
          uses: docker/build-push-action@v2
          with:
            context: './'
            push: true
            tags: ghcr.io/${{ inputs.working-repo }}/${{ inputs.image-name }}:0.0.${{ github.run_number }}
            #labels: ${{ steps.meta.outputs.labels }}
