name: "Build For Template"
on:
  workflow_call:
    inputs:
      self-hosted:
        required: true
        type: boolean
      runner-labels:
        required: true
        type: string
      image-name:
        required: true
        type: string
      environment-name:
        required: true
        type: string
        default: 'AZURE_ENV'
      context:
        required: true
        type: string
        default: '.'
    outputs:
      image-and-tag:
        description: "This contains the image with the tag when performing the build"
        value: ${{ jobs.docker-build.outputs.image-and-tag }}
    secrets: 
      reg_name:
        required: true
      reg_username:
        required: true
      reg_password:
        required: true
    #  envPAT:
    #    required: true

jobs:
  check-inputs: 
    name: Check Inputs
    runs-on: [ '${{ fromJSON(inputs.runner-labels).*.label }}' ]
    steps:
    - name: Display Inputs 
      run: | 
        echo ${{ inputs.self-hosted}}
        echo ${{ inputs.runner-labels}}
        echo ${{ fromJSON(inputs.runner-labels).*.label }}
        echo ${{ inputs.image-name}}
        echo ${{ inputs.context}}
        echo --------------ENV-SECRETS
        echo ${{ secrets.reg_name }}
        echo ${{ secrets.reg_username }}
        echo ${{ secrets.reg_password }}
  docker-build:
    runs-on: [ '${{ fromJSON(inputs.runner-labels).*.label }}' ]
    name: "Docker Build"
    needs: check-inputs
    environment: ${{ inputs.environment-name }} 
    outputs:
      image-and-tag: ${{ steps.get-image-name.outputs.image-and-tag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        if: ${{ inputs.self-hosted == true }}
        uses: docker/setup-buildx-action@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.reg_name }} 
          username: ${{ secrets.reg_username }}
          password: ${{ secrets.reg_password }}
      - name: Create image name
        id: get-image-name
        run: | 
          echo ${{ secrets.reg_name }}/${{ inputs.image-name }}-${GITHUB_REF#refs/heads/}:0.0.${{ github.run_number }}
          echo "::set-output name=image-and-tag::${{ inputs.image-name }}-${GITHUB_REF#refs/heads/}:0.0.${{ github.run_number }}"
      - name: Print Output
        run: | 
          echo ${{ steps.get-image-name.outputs.image-and-tag }}
      - name: Build and push Docker image for server
        uses: docker/build-push-action@v2
        with:
          context: ${{ inputs.context }} 
          push: true
          tags: ${{ secrets.reg_name }}/${{steps.get-image-name.outputs.image-and-tag}}
            #labels: ${{ steps.meta.outputs.labels }}
