name: "Build For Template"
on:
  workflow_call:
    inputs:
      self-hosted:
        required: true
        type: boolean
      label:
        required: true
        type: string
      language:
        required: true
        type: string
      fail-severity:
        required: true
        type: string
      continue-on-err:
        required: true
        type: boolean
        default: false
jobs:
  check-inputs: 
    name: Check Inputs
    runs-on: ${{ inputs.label}} 
    steps:
    - name: Display Inputs 
      run: | 
        echo ${{ inputs.self-hosted}}
        echo ${{ inputs.label}}
        echo ${{ inputs.language}}
        echo ${{ inputs.fail-severity}}
        echo ${{ inputs.continue-on-err}}
  dependency-review:
    runs-on: ${{ inputs.label}} 
    continue-on-error: ${{ inputs.continue-on-err }} == 'true'
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - name: Dependency Review
        uses: actions/dependency-review-action@v2
        with:
          # Possible values: "critical", "high", "moderate", "low"
          fail-on-severity: ${{ inputs.fail-severity}}
          #
          # You can only can only include one of these two options: `allow-licenses` and `deny-licences`
          #
          # Possible values: Any `spdx_id` value(s) from https://docs.github.com/en/rest/licenses
          # allow-licenses: GPL-3.0, BSD-3-Clause, MIT
          #
          # Possible values: Any `spdx_id` value(s) from https://docs.github.com/en/rest/licenses
          # deny-licenses: LGPL-2.0, BSD-2-Clause
